### ISSUE TITLE
Can't browse any snap

### ISSUE THREAD

**Issue by Schlicki2808** [fredldotme/snapz0r#3]
When I search for a snap, e.g. "snap-store", it does not find anything. Did I miss anything?

Device: Google Pixel 3a with Ubuntu Touch 20.04 OTA-3

**Comment by fredldotme** [comment]
Mind running `snap list` (without sudo) in the terminal app and send me a screenshot? Does it ask for the PIN/password in a bubble at the top or not?

**Comment by Schlicki2808** [comment]
This is the output:

`phablet@ubuntu-phablet:~$ snap list
error: cannot list snaps: cannot communicate with server: Get http://localhost/v2/snaps: dial unix /run/snapd.socket: connect: no such file or directory`

**Comment by fredldotme** [comment]
Something in your system is seriously borked, happened to have modified it recently? I'd suggest reflashing (without checking wipe) using the installer.

**Comment by fredldotme** [comment]
In case you want to try something else first, how about: `sudo systemctl --now enable snapd`

**Comment by Schlicki2808** [comment]
This worked! :-) Thank you!
