### ISSUE TITLE
OP 5T

### ISSUE THREAD

**Issue by mihaelmilea** [fredldotme/snapz0r#4]
On my Oneplus 5T, OTA3 stable, it says the kernel is ok, I click on Enable, it says that it's installing and then it reboots and then when I open the program nothing changed, it says the same things. I went through this twice, no progress.

`sudo systemctl --now enable snapd` says "snapd.service does not exist".

Thank you in advance for any help!

**Comment by fredldotme** [comment]
Best check your `/var/log/apt/` directory for any failures that happened during the installation.

**Comment by Altokos** [comment]
I have the same issue on my OnePlus 6T

Wich data do you want from term.log ?

**Comment by mihaelmilea** [comment]
Best advice! Thank you! - in /var/log/apt/term.log I saw "failed to write (No space left on device)" - after I solved that, I was able to browse apps in the snap store. Thanks again!

**Comment by Altokos** [comment]
How did you solved that ? I have over 200Gb of free space on my phone

**Comment by mihaelmilea** [comment]
I "solved" it in a way that is not a good example to anybody: with `df -h` I saw that I had only 54M on / so I decided to move the foder /usr/lib/aarch64-linux-gnu/ to my home folder thinking that it's not needed - after which ubtouch didn't boot anymore - so I installed ubtouch again with the installer (without wipe) and I think after that there were some 400M free on /.

So... :)
