### ISSUE TITLE
Snaps Wont Install Through GUI

### ISSUE THREAD

**Issue by himehowareu** [fredldotme/snapz0r#6]
device : Jingpad 
version: 20.04
branch: stable 

when I tap the install button in the app it will look like it is installing then will stop and it hasn't installed it.

I first notice this bug when i was trying to install a snap that required `  --classic ` . I a m not sure if that had anything to do with it not installing. However this happens for all app as of right now.

**Comment by fredldotme** [comment]
Yes, classic snaps currently aren't installable via Snapz0r, I'd like a warning to show up when one is selected. The "all subsequent snaps fail" part makes me wonder though.

**Comment by himehowareu** [comment]
After a reboot and a little looking around in my configs ( was playing with some stuff ) the error was human. Everything is working as intended.
